import networkx as nx
graph = nx.MultiDiGraph()
graph.add_node('input')
graph.add_node('hidden1')
graph.add_node('output1')
graph.add_node('hidden2')
graph.add_node('output2')
graph.add_node('hidden3')
graph.add_node('output3')
graph.add_edge('input','hidden1')
graph.add_edge('hidden1','output1')
graph.add_edge('hidden1','hidden2')
graph.add_edge('hidden2','output2')
graph.add_edge('hidden2','hidden3')
graph.add_edge('hidden3','output3')
graph_pydot = nx.nx_pydot.to_pydot(graph)
graph_pydot.write('3SAEs.png',format='png',prog='dot')
